name: My sql connection test
on:
  push:
    branches: ["main"]

jobs:
  mysql test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: RUN script
        uses: node index.js
